USE customer_behavior;
SELECT * FROM customer limit 20;
#Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
#Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer
where discount_applied= 'yes'
and purchase_amount> (select avg(purchase_amount) from customer);
#Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, avg(review_rating) as avg_rating
from customer
group by item_purchased
order by avg_rating desc
limit 5;
#Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) as avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;
#Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status , avg(purchase_amount) as avg_spend, sum(purchase_amount) as total_revenue
from customer
group by subscription_status;
#Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased , round(avg(discount_applied='yes')*100,2) as discount_percent
from customer
group by item_purchased
order by discount_percent desc
limit 5;
#Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select
max(previous_purchases) as max_purchases,
min(previous_purchases) as min_purchases
from customer;
select 
case 
 when previous_purchases between 0 and 10 then 'New'
 when previous_purchases between 11 and 30 then 'Returning'
 else 'Loyal'
end as customer_segments, count(*) as customer_count
from customer
group by customer_segments
order by customer_count desc;

#Q8. What are the top 3 most purchased products within each category?
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category, 
           item_purchased, 
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY category 
               ORDER BY COUNT(*) DESC
           ) AS rn
    FROM customer
    GROUP BY category, item_purchased
) AS ranked
WHERE rn <= 3;
#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers 
from customer
where previous_purchases>5
group by subscription_status;
#Q10. What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;